docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
aws_cli_zip_url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
aws_cli_zip_dest: "/tmp/awscliv2.zip"
aws_cli_unzip_dest: "/tmp"
aws_region: "us-east-1"
aws_account_id: "058264170818"  # get from terraform output
ecr_registry: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com"